# Generated by Django 5.0 on 2023-12-31 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_add',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='updated_add',
            new_name='updated_at',
        ),
    ]
